name: "Documentation"

on:
  workflow_call:

jobs:
  deploy:
    permissions:
      pages: "write"
      id-token: "write"
    environment:
      name: "github-pages"
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"

      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: '3.x'

      - name: "Install requirements"
        run: "make doc/prepare"

      - name: "Build site"
        run: "make doc/build"

      - name: "Upload artifact"
        uses: "actions/upload-pages-artifact@v3"
        with:
          path: "./site"

      - name: "Deploy to GitHub Page"
        id: "deployment"
        uses: "actions/deploy-pages@v4"
