name: "Release"

on:
  workflow_call:
    inputs:
      release_name:
        type: "string"
        default: ""

jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"

      - name: "Download build artifacts"
        uses: "actions/download-artifact@v4"
        with:
          path: "build/out/"
          pattern: "sdvg-*"
          merge-multiple: true

      - name: "Extract release notes for ${{ inputs.release_name }}"
        env:
          RELEASE_NAME: "${{ inputs.release_name }}"
        run: |
          awk "/^## .*$RELEASE_NAME/ { flag=1; next } /^## / { flag=0 } flag" CHANGELOG.md > release-notes.txt
          if [ -z "$(grep -vE '^$' release-notes.txt || echo)" ]; then
            echo "No changes since last release" > release-notes.txt
          fi

      - name: "Remove old version of release"
        if: "${{ inputs.release_name == 'latest' }}"
        uses: "dev-drprasad/delete-tag-and-release@v1.1"
        with:
          tag_name: "${{ inputs.release_name }}"
          github_token: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Create release"
        uses: "softprops/action-gh-release@v2"
        with:
          tag_name: "${{ inputs.release_name }}"
          body_path: "release-notes.txt"
          files: "build/out/sdvg-*"
          prerelease: "${{ inputs.release_name == 'latest' }}"
          make_latest: "${{ inputs.release_name != 'latest' }}"
